#!/usr/bin/env python3
"""
Split data.js into data-core.js (sync) + data-detail.js (async).

Core fields (needed for filtering, charts, table rendering):
  i, fn, t, fa, la, y, cc, vt, cf, eo, ve, de, ue, ce, co, ib, ie, id, mp, cu, rg, ln, rv, lm, cs

Detail fields (only needed for paper detail expansion):
  ab, bn, wm, url, doi, du

Also optimizes embedded paper objects in normative/moralPsych/religious sections
by stripping fields available through DATA._paperByFn lookup.

Usage:
    python3 split_data.py            # reads data.js, writes data-core.js + data-detail.js
    python3 split_data.py data.js    # specify input file
"""

import json
import sys
import os

CORE_FIELDS = {'i', 'fn', 't', 'fa', 'la', 'y', 'cc', 'vt', 'cf',
               'eo', 've', 'de', 'ue', 'ce', 'co',
               'ib', 'ie', 'id',
               'mp', 'cu', 'rg', 'ln', 'rv', 'lm', 'cs'}

DETAIL_FIELDS = {'ab', 'bn', 'wm', 'url', 'doi', 'du'}

# Section-specific fields to keep on embedded papers (everything else resolved via _paperByFn)
SECTION_KEEP = {'fn', 'fws', 'th', 'tr', 'kw', 'st', 'd', 'al', 'mt', 'ins'}


def strip_paper_core(paper):
    """Return paper with only core fields."""
    return {k: v for k, v in paper.items() if k in CORE_FIELDS}


def strip_paper_detail(paper):
    """Return detail fields for a paper (only non-empty values)."""
    detail = {}
    for k in DETAIL_FIELDS:
        v = paper.get(k)
        if v:
            detail[k] = v
    return detail


def strip_embedded_paper(paper):
    """Strip embedded paper to section-specific fields + fn only."""
    return {k: v for k, v in paper.items() if k in SECTION_KEEP}


def _is_paper_list(v):
    """Check if a value is a list of paper objects (has 'fn' key)."""
    return isinstance(v, list) and v and isinstance(v[0], dict) and 'fn' in v[0]


def optimize_section(section):
    """Recursively strip embedded papers in a section dict.
    Matches both 'papers' and '*_papers' keys (e.g., 've_de_papers', 'any_papers').
    """
    if isinstance(section, dict):
        result = {}
        for k, v in section.items():
            if (k == 'papers' or k.endswith('_papers')) and _is_paper_list(v):
                result[k] = [strip_embedded_paper(p) for p in v]
            elif isinstance(v, dict):
                result[k] = optimize_section(v)
            else:
                result[k] = v
        return result
    return section


def main():
    input_file = sys.argv[1] if len(sys.argv) > 1 else 'data.js'
    output_dir = os.path.dirname(input_file) or '.'

    # Read and parse data.js
    with open(input_file) as f:
        content = f.read()

    # Extract JSON from "const DATA = {...};"
    json_start = content.index('{')
    json_str = content[json_start:].rstrip().rstrip(';')
    data = json.loads(json_str)

    # Extract header comment
    header = content[:json_start].strip()

    # --- Build core data ---
    core = {}
    core['generated'] = data['generated']

    # Papers: core fields only
    core['papers'] = [strip_paper_core(p) for p in data['papers']]

    # Aggregates and chart data: pass through
    for key in ['agg', 'conf', 'taxonomy', 'cultural', 'llm', 'authors']:
        if key in data:
            core[key] = data[key]

    # Normative/moralPsych/religious: optimize embedded papers
    for key in ['normative', 'moralPsych', 'religious']:
        if key in data:
            core[key] = optimize_section(data[key])

    # --- Build detail data ---
    detail = {}
    for p in data['papers']:
        d = strip_paper_detail(p)
        if d:
            detail[p['i']] = d

    # --- Write files ---
    core_json = json.dumps(core, separators=(',', ':'), ensure_ascii=False)
    detail_json = json.dumps(detail, separators=(',', ':'), ensure_ascii=False)

    core_path = os.path.join(output_dir, 'data-core.js')
    detail_path = os.path.join(output_dir, 'data-detail.js')

    with open(core_path, 'w') as f:
        f.write(f'// Generated by split_data.py from {os.path.basename(input_file)}\n')
        f.write(f'const DATA = {core_json};\n')

    with open(detail_path, 'w') as f:
        f.write(f'// Detail data (async) — generated by split_data.py\n')
        f.write(f'const DATA_DETAIL = {detail_json};\n')
        f.write('if (typeof _onDetailLoaded === "function") _onDetailLoaded();\n')

    # Stats
    core_size = os.path.getsize(core_path)
    detail_size = os.path.getsize(detail_path)
    orig_size = os.path.getsize(input_file)

    print(f'Original:    {orig_size:>10,} bytes ({orig_size/1024:.0f} KB)')
    print(f'Core:        {core_size:>10,} bytes ({core_size/1024:.0f} KB)')
    print(f'Detail:      {detail_size:>10,} bytes ({detail_size/1024:.0f} KB)')
    print(f'Combined:    {core_size+detail_size:>10,} bytes ({(core_size+detail_size)/1024:.0f} KB)')
    print(f'Core papers: {len(core["papers"])} entries, {len(CORE_FIELDS)} fields each')
    print(f'Detail:      {len(detail)} entries with detail data')
    print()
    print(f'Initial payload reduction: {orig_size - core_size:,} bytes ({(orig_size - core_size) / orig_size * 100:.1f}%)')


if __name__ == '__main__':
    main()
